#computation of tables and graphs-summary statistics for employee data
empid=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15)
age=c(30,37,45,32,50,60,35,32,34,43,32,30,43,50,60)
sex=c(0,1,0,1,1,1,0,0,1,0,0,1,1,0,0)
status=c(1,1,2,2,1,1,1,2,2,1,2,1,2,1,2)
empinfo=data.frame(empid,age,sex,status)
empinfo$sex=factor(empinfo$sex,labels=c("male","female"))
empinfo$status=factor(empinfo$status,labels=c("staff","faculty"))
sexm=subset(empinfo,empinfo$sex=='male')
sexf=subset(empinfo,empinfo$sex=='female')
a=summary(empinfo)
b=summary(sexm)
c=summary(sexf)
table1=table(empinfo$sex)
table2=table(empinfo$status)
table3=table(empinfo$sex,empinfo$status)
plot(empinfo$age,type = 'l',main = 'age of subjects',xlab='empid',ylab='age in years',col='blue')
table4=table(empinfo$sex)
pie(table4)
table5=table(empinfo$sex,empinfo$status)
barplot(table5,beside=T,xlim=c(1,15),ylim=c(0,5))
legend("topright",legend=rownames(table5),fill=c('blue','red'),bty='n')
boxplot(empinfo$age~empinfo$status,col=c('red','blue'))
